name: ${javaplugin.name}
main: ${javaplugin.main}
description: ${javaplugin.description}
api-version: 1.13
author: BingoRufus
version: ${project.version}
depend: [ ProtocolLib ]
softdepend: [ DiscordSRV ]
load: POSTWORLD

commands:
  viewdisplay:
    description: See what item a player is displaying
    usage: /<command> <player/id>
    aliases: [ viewitem,viewinv,viewinventory,viewec,viewenderchest,displayview ]
  chatitemreload:
    usage: /<command>
    description: Reload the ChatItemDisplay config
  displayitem:
    usage: /<command>
    description: Display your items in chat
  displayinventory:
    usage: /<command>
    description: Display your inventory
  displayenderchest:
    usage: /<command>
    description: Display your ender chest
    aliases: [ displayec, displayendchest ]
  generatedebuglog:
    usage: /<command>
    description: Generate a debug log, used for creating bug reports
    aliases: [ generatedebuglogs ]
    permission: chatitemdisplay.command.debug

permissions:
  chatitemdisplay.*:
    description: Parent node to all ChatItemDisplay permissions
    default: op
    children:
      chatitemdisplay.command.*:
        description: All ChatItemDisplay commands
        default: op
        children:
          chatitemdisplay.command.reload:
            description: Reload the config
            default: op
          chatitemdisplay.command.debug:
            description: Create debug logs
            default: op
          chatitemdisplay.command.display.*:
            description: Display commands
            default: true
            children:
              chatitemdisplay.command.display.item:
                description: Display items
              chatitemdisplay.command.display.inventory:
                description: Display player inventories
              chatitemdisplay.command.display.enderchest:
                description: Display Ender Chests
      chatitemdisplay.display.*:
        description: Display Objects
        default: true
        children:
          chatitemdisplay.display.item:
            description: Display items
          chatitemdisplay.display.inventory:
            description: Display player inventories
          chatitemdisplay.display.enderchest:
            description: Display Ender Chests
      chatitemdisplay.cooldownbypass:
        description: Bypass the display cooldown
        default: op
      chatitemdisplay.blacklistbypass:
        description: Display blacklisted items
        default: op