name: ChatItemDisplay
main: me.BingoRufus.ChatDisplay.ChatItemDisplay
description: Display items in chat
api-version: 1.13
author: BingoRufus
version: 1.4.4
softdepend: [ProtocolLib]
load: POSTWORLD
commands:
  viewitem:
    description: See what item a player is displaying
    usage: /<command> <player>
  chatitemreload:
    description: Reload the ChatItemDisplay config
  displayitem:
    usage: /<command>
    permission: chatitemdisplay.display
    description: Display your items in chat
    aliases: [display]
permissions:
  ChatItemDisplay.*:
    description: Parent node to all ChatItemDisplay permissions
    default: op
    children:
      ChatItemDisplay.reload:
        description: Reload the ChatItemDisplay config
        default: op
      ChatItemDisplay.display:
        description: Display Items using one of the Triggers in the config.yml
        default: true
      ChatItemDisplay.cooldownbypass:
        description: Bypass the display cooldown
        default: op
      ChatItemDisplay.blacklistbypass:
        description: Display blacklisted items
        default: op